version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.6

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/node:18.0.0-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
    working_directory: ~/apollo-mock-http

    steps:
      - checkout

      - run: yarn
      
      - run:
          name: Danger
          command: 
            yarn danger ci
            danger

      # run tests
      - run:
          name: "Run tests"
          command: yarn test

      # run build
      - run: yarn build

      - persist_to_workspace:
          root: .
          paths:
            - .

  release:
    docker:
      - image: cimg/node:18.0.0-browsers
    steps:
      - attach_workspace:
          at: .
      - run: npx semantic-release

  coverage:
    docker:
      - image: cimg/node:18.0.0-browsers
    steps:
      - attach_workspace:
          at: .
      - run: yarn test:coverage
      - store_artifacts:
          path: coverage
notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=${process.env.COVERALLS_REPO_TOKEN}

workflows:
  version: 2
  build:
    jobs:
      - build
      - coverage:
          requires:
            - build
          filters:
            branches:
              only:
                - main
      - release:
          requires:
            - coverage
          filters:
            branches:
              only:
                - main
